# Common tasks for Raspbian OS hosts.
---
- name: Update to latest Raspberry Pi stock kernel and bootloader.
  when: not hardened_hosts | default('true')
  apt:
    update_cache: true
    name: "{{ item }}"
    state: latest
  loop:
    - raspberrypi-kernel
    - raspberrypi-bootloader
  notify: reboot

# TODO: Figure out how to script disabling the hardware interfaces
#       of the RPi version 3 hardware.
#
#       Of possible interest to do this is to read and learn from
#       https://www.raspberrypi.org/documentation/configuration/device-tree.md
#
#- name: Disable unnecessary hardware interfaces
#  command: dtparam spi=off
