# Common tasks for Debian-derived operating systems.
---
- name: Check for Raspberry Pi OS.
  register: rpi_issue
  stat:
    path: /etc/rpi-issue
    get_checksum: false

- name: Set host as Raspberry Pi OS.
  set_fact:
      raspberry_pi_os: true

- name: Include Raspberry Pi OS-specific tasks.
  when: raspberry_pi_os
  import_tasks: common-raspberry-pi-os.yaml
