# Reboot handler. In its own file due to Ansible's lack of support
# for the `block` key in a handler. We don't yet make use of the
# `reboot` module available in Ansible 2.7+ because it doesn't always
# reliably reconnect after execution. :(
---
- name: Reboot.
  block:
    - name: Reboot system.
      shell: "sleep 5 && shutdown -r now"
      async: 1
      poll: 0
    - name: Wait for system to reboot.
      wait_for_connection:
        delay: 20
        sleep: 5
        timeout: 180
